# Generated by Django 4.2.2 on 2023-06-29 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("audio_example", models.FileField(default="", upload_to="")),
                ("audio_myvoice", models.FileField(default="", upload_to="")),
                ("title", models.CharField(default="", max_length=500)),
                ("ko_title", models.CharField(default="", max_length=500)),
                ("content", models.TextField()),
                ("ko_content", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_result",
            },
        ),
    ]
